"""Tests for ``strip_git_history``.

Covers Issue #84: an agent under SWE-bench evaluation must not be able to
recover the upstream reference fix by inspecting git history.
"""

from __future__ import annotations

import os
import subprocess
from pathlib import Path

import pytest

from swebench.harness import strip_git_history


def _git(repo: str, *args: str, check: bool = True) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", "-C", repo, *args],
        capture_output=True,
        text=True,
        check=check,
    )


def _make_repo(root: Path) -> str:
    """Build a throwaway repo with a multi-commit history and return its path.

    Layout: 3 commits on ``main``, plus a feature branch with one extra
    commit, plus an annotated tag, plus a fake remote-tracking ref, plus a
    populated reflog.
    """
    repo = root / "repo"
    repo.mkdir()
    _git(str(repo), "init", "-q", "-b", "main")
    _git(str(repo), "config", "user.email", "test@test")
    _git(str(repo), "config", "user.name", "test")

    (repo / "a.txt").write_text("one\n")
    _git(str(repo), "add", "a.txt")
    _git(str(repo), "commit", "-q", "-m", "commit one")

    (repo / "a.txt").write_text("two\n")
    _git(str(repo), "add", "a.txt")
    _git(str(repo), "commit", "-q", "-m", "commit two — REFERENCE FIX")

    (repo / "b.txt").write_text("three\n")
    _git(str(repo), "add", "b.txt")
    _git(str(repo), "commit", "-q", "-m", "commit three")

    # Feature branch with an extra commit — its tip must also disappear.
    _git(str(repo), "branch", "feature")
    _git(str(repo), "checkout", "-q", "feature")
    (repo / "c.txt").write_text("feat\n")
    _git(str(repo), "add", "c.txt")
    _git(str(repo), "commit", "-q", "-m", "feature work")
    _git(str(repo), "checkout", "-q", "main")

    # Annotated tag pointing at the reference-fix commit.
    _git(str(repo), "tag", "-a", "v1.0", "HEAD~1", "-m", "release")

    # Fake remote-tracking ref.
    head_sha = _git(str(repo), "rev-parse", "HEAD").stdout.strip()
    _git(str(repo), "update-ref", "refs/remotes/origin/main", head_sha)

    return str(repo)


def test_strip_leaves_single_orphan_commit(tmp_path: Path) -> None:
    repo = _make_repo(tmp_path)
    pre_tree = _git(repo, "rev-parse", "HEAD^{tree}").stdout.strip()

    strip_git_history(repo)

    # Exactly one commit reachable via any ref.
    count = _git(repo, "rev-list", "--all", "--count").stdout.strip()
    assert count == "1", f"expected 1 reachable commit, got {count}"

    log = _git(repo, "log", "--all", "--oneline").stdout.strip().splitlines()
    assert len(log) == 1, f"expected 1 log line, got {log!r}"

    # The orphan commit has no parents.
    parents = _git(repo, "rev-list", "--parents", "-n", "1", "HEAD").stdout.strip().split()
    assert len(parents) == 1, f"orphan should have no parents, got {parents!r}"

    # Tree is preserved — same worktree content.
    post_tree = _git(repo, "rev-parse", "HEAD^{tree}").stdout.strip()
    assert pre_tree == post_tree


def test_strip_removes_alternates_and_reflog_and_packedrefs(tmp_path: Path) -> None:
    repo = _make_repo(tmp_path)

    # Seed packed-refs and an alternates file so we can verify removal.
    _git(repo, "pack-refs", "--all")
    assert os.path.isfile(os.path.join(repo, ".git", "packed-refs"))

    alternates_dir = os.path.join(repo, ".git", "objects", "info")
    os.makedirs(alternates_dir, exist_ok=True)
    alternates_path = os.path.join(alternates_dir, "alternates")
    # Point at a real-ish objects dir (won't be followed since we'll delete it).
    Path(alternates_path).write_text("/nonexistent/objects\n")

    # Reflog exists by default after the commits above.
    assert os.path.isdir(os.path.join(repo, ".git", "logs"))

    strip_git_history(repo)

    # packed-refs may be regenerated by `git gc` at the end of the strip —
    # but if it exists it must only reference the orphan commit, never any
    # pre-strip SHA.
    packed_refs = os.path.join(repo, ".git", "packed-refs")
    if os.path.exists(packed_refs):
        orphan_sha = _git(repo, "rev-parse", "HEAD").stdout.strip()
        contents = Path(packed_refs).read_text()
        for line in contents.splitlines():
            line = line.strip()
            if not line or line.startswith("#") or line.startswith("^"):
                continue
            sha = line.split()[0]
            assert sha == orphan_sha, (
                f"packed-refs references non-orphan SHA {sha}: {line!r}"
            )
    assert not os.path.exists(alternates_path)
    assert not os.path.exists(os.path.join(repo, ".git", "logs"))


def test_strip_removes_branches_tags_and_remote_refs(tmp_path: Path) -> None:
    repo = _make_repo(tmp_path)

    strip_git_history(repo)

    # Only the current branch should remain; feature, tags, remotes gone.
    refs = _git(repo, "for-each-ref", "--format=%(refname)").stdout.splitlines()
    refs = [r.strip() for r in refs if r.strip()]
    assert refs == ["refs/heads/main"], f"unexpected refs: {refs!r}"

    # No tags and no remote-tracking refs.
    tags = _git(repo, "tag", "-l").stdout.strip()
    assert tags == ""

    remotes = _git(
        repo, "for-each-ref", "--format=%(refname)", "refs/remotes/"
    ).stdout.strip()
    assert remotes == ""


def test_strip_preserves_working_tree_and_agent_can_commit(tmp_path: Path) -> None:
    repo = _make_repo(tmp_path)
    a_contents = (Path(repo) / "a.txt").read_text()
    b_contents = (Path(repo) / "b.txt").read_text()

    strip_git_history(repo)

    # Working tree files untouched.
    assert (Path(repo) / "a.txt").read_text() == a_contents
    assert (Path(repo) / "b.txt").read_text() == b_contents

    # git status / diff should work with no errors and report a clean tree.
    status = _git(repo, "status", "--porcelain")
    assert status.stdout == "", f"expected clean tree, got: {status.stdout!r}"

    # Agent edits + commit must work (no object-not-found errors).
    (Path(repo) / "agent.txt").write_text("hi\n")
    _git(repo, "add", "agent.txt")
    _git(repo, "commit", "-q", "-m", "agent change")

    # Now history should have exactly 2 commits (orphan + agent).
    count = _git(repo, "rev-list", "--all", "--count").stdout.strip()
    assert count == "2"


def test_strip_is_idempotent(tmp_path: Path) -> None:
    repo = _make_repo(tmp_path)
    strip_git_history(repo)
    sha_after_first = _git(repo, "rev-parse", "HEAD").stdout.strip()

    # Second call is a no-op at the ref level: same orphan SHA, still 1 commit.
    strip_git_history(repo)
    sha_after_second = _git(repo, "rev-parse", "HEAD").stdout.strip()
    count = _git(repo, "rev-list", "--all", "--count").stdout.strip()

    assert count == "1"
    assert sha_after_first == sha_after_second, (
        "orphan SHA should be deterministic given identical tree + fixed author/date"
    )


def test_strip_does_not_touch_alternates_source(tmp_path: Path) -> None:
    """A bare repo lent via alternates must not be mutated by the strip."""
    bare = tmp_path / "bare.git"
    bare.mkdir()
    _git(str(bare), "init", "-q", "--bare", "-b", "main")

    # Seed the bare repo with a commit via an intermediate clone.
    seed = tmp_path / "seed"
    seed.mkdir()
    _git(str(seed), "init", "-q", "-b", "main")
    _git(str(seed), "config", "user.email", "test@test")
    _git(str(seed), "config", "user.name", "test")
    (seed / "f.txt").write_text("seed\n")
    _git(str(seed), "add", "f.txt")
    _git(str(seed), "commit", "-q", "-m", "seed commit — SHOULD SURVIVE")
    _git(str(seed), "remote", "add", "origin", str(bare))
    _git(str(seed), "push", "-q", "origin", "main")

    # Local-shared clone — uses alternates back to the bare repo.
    shared = tmp_path / "shared"
    subprocess.run(
        ["git", "clone", "--local", "--shared", "--quiet", str(bare), str(shared)],
        check=True,
    )
    assert os.path.isfile(str(shared / ".git" / "objects" / "info" / "alternates"))

    # Record a pre-strip object id in the bare repo so we can verify it survives.
    bare_head = _git(str(bare), "rev-parse", "HEAD").stdout.strip()

    strip_git_history(str(shared))

    # Bare repo is untouched — the pre-strip commit is still retrievable.
    assert _git(str(bare), "rev-parse", bare_head).stdout.strip() == bare_head
    bare_count = _git(str(bare), "rev-list", "--all", "--count").stdout.strip()
    assert bare_count == "1"

    # And the shared clone now has its own 1-commit orphan history — no
    # alternates link back to the bare repo.
    assert not os.path.exists(
        str(shared / ".git" / "objects" / "info" / "alternates")
    )
    shared_count = _git(str(shared), "rev-list", "--all", "--count").stdout.strip()
    assert shared_count == "1"


def test_strip_works_when_head_is_detached(tmp_path: Path) -> None:
    repo = _make_repo(tmp_path)
    # Detach HEAD at the previous commit.
    _git(repo, "checkout", "-q", "HEAD~1")

    strip_git_history(repo)

    count = _git(repo, "rev-list", "--all", "--count").stdout.strip()
    assert count == "1"
    # HEAD should be a valid commit.
    _git(repo, "rev-parse", "HEAD")
