"""Tests for ``strip_git_history``.

Covers Issue #84: an agent under SWE-bench evaluation must not be able to
recover the upstream reference fix by inspecting git history.
"""

from __future__ import annotations

import os
import subprocess
from pathlib import Path

import pytest

from swebench.harness import apply_test_patch, strip_git_history


def _git(repo: str, *args: str, check: bool = True) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", "-C", repo, *args],
        capture_output=True,
        text=True,
        check=check,
    )


def _make_repo(root: Path) -> str:
    """Build a throwaway repo with a multi-commit history and return its path.

    Layout: 3 commits on ``main``, plus a feature branch with one extra
    commit, plus an annotated tag, plus a fake remote-tracking ref, plus a
    populated reflog.
    """
    repo = root / "repo"
    repo.mkdir()
    _git(str(repo), "init", "-q", "-b", "main")
    _git(str(repo), "config", "user.email", "test@test")
    _git(str(repo), "config", "user.name", "test")

    (repo / "a.txt").write_text("one\n")
    _git(str(repo), "add", "a.txt")
    _git(str(repo), "commit", "-q", "-m", "commit one")

    (repo / "a.txt").write_text("two\n")
    _git(str(repo), "add", "a.txt")
    _git(str(repo), "commit", "-q", "-m", "commit two — REFERENCE FIX")

    (repo / "b.txt").write_text("three\n")
    _git(str(repo), "add", "b.txt")
    _git(str(repo), "commit", "-q", "-m", "commit three")

    # Feature branch with an extra commit — its tip must also disappear.
    _git(str(repo), "branch", "feature")
    _git(str(repo), "checkout", "-q", "feature")
    (repo / "c.txt").write_text("feat\n")
    _git(str(repo), "add", "c.txt")
    _git(str(repo), "commit", "-q", "-m", "feature work")
    _git(str(repo), "checkout", "-q", "main")

    # Annotated tag pointing at the reference-fix commit.
    _git(str(repo), "tag", "-a", "v1.0", "HEAD~1", "-m", "release")

    # Fake remote-tracking ref.
    head_sha = _git(str(repo), "rev-parse", "HEAD").stdout.strip()
    _git(str(repo), "update-ref", "refs/remotes/origin/main", head_sha)

    return str(repo)


def test_strip_leaves_single_orphan_commit(tmp_path: Path) -> None:
    repo = _make_repo(tmp_path)
    pre_tree = _git(repo, "rev-parse", "HEAD^{tree}").stdout.strip()

    strip_git_history(repo)

    # Exactly one commit reachable via any ref.
    count = _git(repo, "rev-list", "--all", "--count").stdout.strip()
    assert count == "1", f"expected 1 reachable commit, got {count}"

    log = _git(repo, "log", "--all", "--oneline").stdout.strip().splitlines()
    assert len(log) == 1, f"expected 1 log line, got {log!r}"

    # The orphan commit has no parents.
    parents = _git(repo, "rev-list", "--parents", "-n", "1", "HEAD").stdout.strip().split()
    assert len(parents) == 1, f"orphan should have no parents, got {parents!r}"

    # Tree is preserved — same worktree content.
    post_tree = _git(repo, "rev-parse", "HEAD^{tree}").stdout.strip()
    assert pre_tree == post_tree


def test_strip_removes_alternates_and_reflog_and_packedrefs(tmp_path: Path) -> None:
    repo = _make_repo(tmp_path)

    # Seed packed-refs and an alternates file so we can verify removal.
    _git(repo, "pack-refs", "--all")
    assert os.path.isfile(os.path.join(repo, ".git", "packed-refs"))

    alternates_dir = os.path.join(repo, ".git", "objects", "info")
    os.makedirs(alternates_dir, exist_ok=True)
    alternates_path = os.path.join(alternates_dir, "alternates")
    # Point at a real-ish objects dir (won't be followed since we'll delete it).
    Path(alternates_path).write_text("/nonexistent/objects\n")

    # Reflog exists by default after the commits above.
    assert os.path.isdir(os.path.join(repo, ".git", "logs"))

    strip_git_history(repo)

    # packed-refs may be regenerated by `git gc` at the end of the strip —
    # but if it exists it must only reference the orphan commit, never any
    # pre-strip SHA.
    packed_refs = os.path.join(repo, ".git", "packed-refs")
    if os.path.exists(packed_refs):
        orphan_sha = _git(repo, "rev-parse", "HEAD").stdout.strip()
        contents = Path(packed_refs).read_text()
        for line in contents.splitlines():
            line = line.strip()
            if not line or line.startswith("#") or line.startswith("^"):
                continue
            sha = line.split()[0]
            assert sha == orphan_sha, (
                f"packed-refs references non-orphan SHA {sha}: {line!r}"
            )
    assert not os.path.exists(alternates_path)
    assert not os.path.exists(os.path.join(repo, ".git", "logs"))


def test_strip_removes_branches_tags_and_remote_refs(tmp_path: Path) -> None:
    repo = _make_repo(tmp_path)

    strip_git_history(repo)

    # Only the current branch should remain; feature, tags, remotes gone.
    refs = _git(repo, "for-each-ref", "--format=%(refname)").stdout.splitlines()
    refs = [r.strip() for r in refs if r.strip()]
    assert refs == ["refs/heads/main"], f"unexpected refs: {refs!r}"

    # No tags and no remote-tracking refs.
    tags = _git(repo, "tag", "-l").stdout.strip()
    assert tags == ""

    remotes = _git(
        repo, "for-each-ref", "--format=%(refname)", "refs/remotes/"
    ).stdout.strip()
    assert remotes == ""


def test_strip_preserves_working_tree_and_agent_can_commit(tmp_path: Path) -> None:
    repo = _make_repo(tmp_path)
    a_contents = (Path(repo) / "a.txt").read_text()
    b_contents = (Path(repo) / "b.txt").read_text()

    strip_git_history(repo)

    # Working tree files untouched.
    assert (Path(repo) / "a.txt").read_text() == a_contents
    assert (Path(repo) / "b.txt").read_text() == b_contents

    # git status / diff should work with no errors and report a clean tree.
    status = _git(repo, "status", "--porcelain")
    assert status.stdout == "", f"expected clean tree, got: {status.stdout!r}"

    # Agent edits + commit must work (no object-not-found errors).
    (Path(repo) / "agent.txt").write_text("hi\n")
    _git(repo, "add", "agent.txt")
    _git(repo, "commit", "-q", "-m", "agent change")

    # Now history should have exactly 2 commits (orphan + agent).
    count = _git(repo, "rev-list", "--all", "--count").stdout.strip()
    assert count == "2"


def test_strip_is_idempotent(tmp_path: Path) -> None:
    repo = _make_repo(tmp_path)
    strip_git_history(repo)
    sha_after_first = _git(repo, "rev-parse", "HEAD").stdout.strip()

    # Second call is a no-op at the ref level: same orphan SHA, still 1 commit.
    strip_git_history(repo)
    sha_after_second = _git(repo, "rev-parse", "HEAD").stdout.strip()
    count = _git(repo, "rev-list", "--all", "--count").stdout.strip()

    assert count == "1"
    assert sha_after_first == sha_after_second, (
        "orphan SHA should be deterministic given identical tree + fixed author/date"
    )


def test_strip_does_not_touch_alternates_source(tmp_path: Path) -> None:
    """A bare repo lent via alternates must not be mutated by the strip."""
    bare = tmp_path / "bare.git"
    bare.mkdir()
    _git(str(bare), "init", "-q", "--bare", "-b", "main")

    # Seed the bare repo with a commit via an intermediate clone.
    seed = tmp_path / "seed"
    seed.mkdir()
    _git(str(seed), "init", "-q", "-b", "main")
    _git(str(seed), "config", "user.email", "test@test")
    _git(str(seed), "config", "user.name", "test")
    (seed / "f.txt").write_text("seed\n")
    _git(str(seed), "add", "f.txt")
    _git(str(seed), "commit", "-q", "-m", "seed commit — SHOULD SURVIVE")
    _git(str(seed), "remote", "add", "origin", str(bare))
    _git(str(seed), "push", "-q", "origin", "main")

    # Local-shared clone — uses alternates back to the bare repo.
    shared = tmp_path / "shared"
    subprocess.run(
        ["git", "clone", "--local", "--shared", "--quiet", str(bare), str(shared)],
        check=True,
    )
    assert os.path.isfile(str(shared / ".git" / "objects" / "info" / "alternates"))

    # Record a pre-strip object id in the bare repo so we can verify it survives.
    bare_head = _git(str(bare), "rev-parse", "HEAD").stdout.strip()

    strip_git_history(str(shared))

    # Bare repo is untouched — the pre-strip commit is still retrievable.
    assert _git(str(bare), "rev-parse", bare_head).stdout.strip() == bare_head
    bare_count = _git(str(bare), "rev-list", "--all", "--count").stdout.strip()
    assert bare_count == "1"

    # And the shared clone now has its own 1-commit orphan history — no
    # alternates link back to the bare repo.
    assert not os.path.exists(
        str(shared / ".git" / "objects" / "info" / "alternates")
    )
    shared_count = _git(str(shared), "rev-list", "--all", "--count").stdout.strip()
    assert shared_count == "1"


def test_strip_works_when_head_is_detached(tmp_path: Path) -> None:
    repo = _make_repo(tmp_path)
    # Detach HEAD at the previous commit.
    _git(repo, "checkout", "-q", "HEAD~1")

    strip_git_history(repo)

    count = _git(repo, "rev-list", "--all", "--count").stdout.strip()
    assert count == "1"
    # HEAD should be a valid commit.
    _git(repo, "rev-parse", "HEAD")


def test_apply_test_patch_leaves_empty_git_diff(tmp_path: Path) -> None:
    """Regression test for Issue #226: test patch must not be visible via git diff.

    After apply_test_patch(), `git diff` and `git diff HEAD` must both return
    empty output so an agent cannot read the test assertions from the diff.
    """
    repo = _make_repo(tmp_path)
    strip_git_history(repo)

    # Create a minimal patch that adds a new test file.
    patch_path = tmp_path / "test.patch"
    patch_path.write_text(
        "diff --git a/test_secret.py b/test_secret.py\n"
        "new file mode 100644\n"
        "index 0000000..e69de29\n"
        "--- /dev/null\n"
        "+++ b/test_secret.py\n"
        "@@ -0,0 +1,3 @@\n"
        "+def test_answer():\n"
        "+    assert answer == 42  # hidden assertion\n"
        "+\n"
    )

    result = apply_test_patch(repo, str(patch_path))
    assert result is True

    # git diff (unstaged changes) must be empty — Issue #226.
    diff = _git(repo, "diff").stdout
    assert diff == "", f"git diff is not empty after apply_test_patch: {diff!r}"

    # git diff HEAD (staged + unstaged vs last commit) must also be empty.
    diff_head = _git(repo, "diff", "HEAD").stdout
    assert diff_head == "", f"git diff HEAD is not empty after apply_test_patch: {diff_head!r}"

    # The patch file itself should exist in the working tree (was applied).
    assert (Path(repo) / "test_secret.py").exists()

    # History should now have exactly 2 commits (orphan base + test patch commit).
    count = _git(repo, "rev-list", "--all", "--count").stdout.strip()
    assert count == "2"


def test_apply_test_patch_resets_agent_edits_to_modified_file(tmp_path: Path) -> None:
    """Issue #287 contamination guard.

    Under the post-agent ordering, the agent might edit the same test file
    the held-out patch modifies.  ``apply_test_patch`` must force-reset
    those files to HEAD before ``git apply`` so the patch lands cleanly —
    otherwise the run would either silently fail-to-apply or, worse, score
    PASS against a tree that doesn't contain the held-out assertions.
    """
    repo = _make_repo(tmp_path)
    # Commit a file with a known body, then orphan-strip so HEAD is the only commit.
    (Path(repo) / "test_target.py").write_text(
        "def test_existing():\n    assert True\n"
    )
    _git(repo, "add", "test_target.py")
    _git(repo, "commit", "-q", "-m", "add target")
    strip_git_history(repo)

    # The held-out patch ADDS an assertion to test_existing.
    patch_path = tmp_path / "tests.patch"
    patch_path.write_text(
        "diff --git a/test_target.py b/test_target.py\n"
        "--- a/test_target.py\n"
        "+++ b/test_target.py\n"
        "@@ -1,2 +1,3 @@\n"
        " def test_existing():\n"
        "     assert True\n"
        "+    assert 42 == 42  # held-out assertion\n"
    )

    # Simulate the agent editing the same file with its own (conflicting) version.
    (Path(repo) / "test_target.py").write_text(
        "def test_existing():\n    pass  # I am the agent, I rewrote this\n"
    )
    # Important: don't commit the agent's edit; in the real harness the
    # agent's edits are unstaged at the point apply_test_patch runs.

    assert apply_test_patch(repo, str(patch_path)) is True, (
        "apply_test_patch must reset the agent's conflicting edit before "
        "git apply and land the patch successfully."
    )

    # The committed tree must reflect the held-out patch, not the agent's edit.
    final = (Path(repo) / "test_target.py").read_text()
    assert "held-out assertion" in final, (
        f"Patch did not land — file contents: {final!r}"
    )
    assert "I am the agent" not in final, (
        f"Agent's contamination survived — file contents: {final!r}"
    )
    # Working tree must be clean (patch was committed, not left as a diff).
    assert _git(repo, "diff").stdout == ""
    assert _git(repo, "diff", "HEAD").stdout == ""


def test_apply_test_patch_removes_agent_created_file_collision(tmp_path: Path) -> None:
    """If the patch creates a new file (``--- /dev/null``) and the agent
    happened to write a file at the same path, ``git apply`` would normally
    fail with "already exists in working directory".  ``apply_test_patch``
    must rm the colliding file so the patch can land.
    """
    repo = _make_repo(tmp_path)
    strip_git_history(repo)

    # Patch creates tests/new_test.py from scratch.
    patch_path = tmp_path / "tests.patch"
    patch_path.write_text(
        "diff --git a/tests/new_test.py b/tests/new_test.py\n"
        "new file mode 100644\n"
        "index 0000000..aaaaaaa\n"
        "--- /dev/null\n"
        "+++ b/tests/new_test.py\n"
        "@@ -0,0 +1,2 @@\n"
        "+def test_new():\n"
        "+    assert True\n"
    )

    # Agent created a file at the same path with different content.
    (Path(repo) / "tests").mkdir(exist_ok=True)
    (Path(repo) / "tests" / "new_test.py").write_text("# agent's file\n")

    assert apply_test_patch(repo, str(patch_path)) is True
    final = (Path(repo) / "tests" / "new_test.py").read_text()
    assert "test_new" in final
    assert "agent's file" not in final


def test_apply_test_patch_returns_false_when_unrecoverable(tmp_path: Path) -> None:
    """If the patch references context the agent obliterated and reset can't
    save us, ``apply_test_patch`` must return False so the caller can score
    the run as FAIL rather than trust a contaminated tree.

    Construct an unrecoverable case: the patch creates ``tests/`` as a file,
    but the agent already created ``tests/`` as a directory containing other
    files — ``os.remove`` will refuse a non-empty directory.
    """
    repo = _make_repo(tmp_path)
    strip_git_history(repo)

    # Patch creates a file at path "tests".
    patch_path = tmp_path / "tests.patch"
    patch_path.write_text(
        "diff --git a/tests b/tests\n"
        "new file mode 100644\n"
        "index 0000000..aaaaaaa\n"
        "--- /dev/null\n"
        "+++ b/tests\n"
        "@@ -0,0 +1 @@\n"
        "+held-out content\n"
    )
    # Agent created "tests" as a directory with an unrelated file inside,
    # so os.remove cannot clear the collision.
    (Path(repo) / "tests").mkdir()
    (Path(repo) / "tests" / "junk.py").write_text("# unrelated\n")

    assert apply_test_patch(repo, str(patch_path)) is False, (
        "apply_test_patch must return False when collision cannot be cleared, "
        "so the caller knows to score the run as FAIL."
    )
